### PR TITLE
feat: basic working version

### PR DESCRIPTION
**Pull request by ToBinio**
This PR adds the functionality needed for a basic working version

### CODE REVIEW

**Review by xFizzar — APPROVED** [review]
No Review requested from me but looks good

**Comment by leToxic** [comment]
1. /stub: maybe change to better fitting name or move content to domain
2. station_query_protocol.py [27:33]: refactor for better readability and add comments for understanding the solved Problem
3. ctx.storage for handling stations: imo a lightweight database is more suitable bc ctx.storage is in memory and maybe would cause future Problems with performance when gas_goblin crashes. gas_golbin should maintain a small database with few data points and save them on local storage. On changes add, change or delete station. In memory solutions are just for debugging and dev imo.
4. asyncio.ensure_future: add comment for better understanding

**Review by leToxic — CHANGES_REQUESTED** [review]
1. /stub: maybe change to better fitting name or move content to domain
2. station_query_protocol.py [27:33]: refactor for better readability and add comments for understanding the solved Problem
3. ctx.storage for handling stations: imo a lightweight database is more suitable bc ctx.storage is in memory and maybe would cause future Problems with performance when gas_goblin crashes. gas_golbin should maintain a small database with few data points and save them on local storage. On changes add, change or delete station. In memory solutions are just for debugging and dev imo.
4. asyncio.ensure_future: add comment for better understanding

**Review by leToxic — APPROVED** [review]

**Comment by ToBinio** [comment]
1:
I feel like `/stub` is a pretty fitting name since it is only there to help debug/test the "real" code - https://en.wikipedia.org/wiki/Method_stub 

---

3:
I agree but I don't think it is necessary for this PR and should be added in a future one

**Pull request merged**
